version: "3.8"

services:
  server:
    build: ./server
    restart: unless-stopped
    volumes: 
      - ./server:/usr/src/server
    ports: 
      - "3000:8080"
    networks: 
      - server-db

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes: 
      - ./db/data:/data/db
    ports: 
      - "5000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks: 
      - server-db
  
networks: 
  server-db:
    driver: bridge